version: "3.1"
services:
  jenkins:
   image: jenkins/jenkins:latest
   container_name: jenkins
   ports:
     - 8080:8080
     - 50000:50000
   volumes:
     - /var/www:/var/jenkins_home/workspace
     - /var/jenkins_home:/var/jenkins_home
   environment:
     - JAVA_OPTS=-Djava.util.logging.config.file=/var/jenkins_home/log.properties

